name: CI

on:
  push:
    branches: [master]
    paths:
      - "./**"
  pull_request:
    branches: [master]
    paths:
      - "./**"

jobs:
  ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.2"

      - name: Install poetry
        run: python3 -m pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: MyPy
        run: poetry run task mypy

      - name: Tests
        run: poetry run task test
